#! /bin/bash

# This line needs to be first for it to get the correct execution  
# path of this script. This is used to dynamically set the data file 
# path for improved portability by avoiding hardcoded paths. This 
# allows the script to be stored anywhere. Users are advised to use 
# a sepatare directory to avoid file collisions with other existing 
# data.dat files.
declare -g script_path=$_;


load_data_file() {
    declare -gA quick_cd_dirs;
    if [ -f $data_file ]; then
        source $data_file;
    else
        quick_cd_dirs=();
    fi
}


write_data_file() {
    echo "# DO NOT EDIT! File automatically generated by script" \
        > $data_file;
    echo "quick_cd_dirs=(\\" >> $data_file;
    for i in "${!quick_cd_dirs[@]}";
    do
        printf "\t[${i}]=${quick_cd_dirs[${i}]} \\" >> $data_file;
        printf "\n" >> $data_file;
    done
    echo ")" >> $data_file;
}

parse_args() {
    declare args=$@
    
    case ${args[0]} in
        "-a")
            add_dir;
            exit 0
            ;;
        "-d")
            delete_dir;
            exit 0
            ;;
    esac
    
}
main() {
    declare args=$@;
    declare -g data_file=$(echo $script_path | grep -oP "/*.+/")data.dat; 

    if [ ${#args[@]} -gt 1 ]; then
        parse_args $args
    elif [ ${#args[@]} -eq 0 ]; then
        print_help
        exit
    elif [ "${quick_cd_dirs["${args[0]}"]}" != "" ]; then
        #TODO: if dir exists
        cd

}

main $@

alias qcd='QuickCD'
QuickCD() {
    if [ "$QDIRS_OPT" = "-a" ]; then
        echo "        #[\"\"]=\"$PWD\" \\" >> \
            ~/.bash_aliases;
    elif [ "$QDIRS_OPT" = "help" ]; then
        printf "Change directory shortcuts.\n";
        printf "Usage: qcd [option]\n\nQuick CD Dirs:\n";
        
        for i in "${!QDIRS[@]}"
        do
            printf "${i}\t${QDIRS[${i}]}\n";
        done
    
    elif [ "${QDIRS["$QDIRS_OPT"]}" != "" ]; then
        cd "${QDIRS["$QDIRS_OPT"]}";
    
    else
        printf "Invalid option\n";
    fi
    
    unset QDIRS_OPT;
    unset QDIRS;
}
