#! /bin/bash

# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms 
# will be:
#
#   1,2,3,4,8,13,21,34,55,89,...
#
# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.


declare -i sum=0

declare -i last=1
declare -i i=1
while [ $i -lt 4000000 ];
do
    i=$(($i+1))
    declare -i next=$(($last+$i))
    last=$i
    i=$next

    if [ $(($i%2)) -eq 0 ]; then
       sum+=$i
    fi
done

echo $sum
